#!/usr/bin/env just --justfile
#
#
# Just command runner configuration
#   - Initial setup: bash ./setup-just-commands-user.sh
#   - Then you can run from any directory (lists all options): ujust
#   - More info at https://github.com/casey/just
#
#

# Set default config

set shell := ["bash", "-uc"]
set ignore-comments := true
set quiet := true

# Add alias commands

alias help := list
alias ls := list
alias menu := choose
alias upgrade := update
alias up := update
alias rm := clean
alias ref := refresh
alias ai := ai-install

# Default to the 'list' command, when 'just' is run without any parameters
[group('just')]
default: list

# Show a graphical selector listing the available options and their script content
[group('just')]
choose:
  @just --choose --justfile "{{ justfile() }}"

# Show a list of the available 'run' commands
[group('just')]
list:
  @echo '{{ style("warning") }}Listing "just" command options from {{ justfile() }}{{ NORMAL }}'
  just --justfile "{{ justfile() }}" --list --alias-style 'right' --list-heading '' --list-prefix ''

# Get the OS name
[group('tools')]
os:
  #!/usr/bin/env bash
  OS="$(uname -s)";
  if [[ "$OS" == 'Freedesktop SDK' ]]; then
    echo 'Linux';
  elif [[ "$OS" == 'Linux' ]]; then
    DISTRO_NAME="$(source /etc/os-release && echo $NAME)";
    if [[ "$DISTRO_NAME" == 'Fedora Linux' ]]; then
      if command -v rpm-ostree &> /dev/null; then
    			echo 'Fedora Atomic';
    		else
      		echo 'Fedora';
      	fi
    elif [[ "$DISTRO_NAME" == 'Debian GNU/Linux' ]]; then
      echo 'Debian';
    elif [[ "$DISTRO_NAME" == 'Linux Mint' ]]; then
      echo 'Mint';
    elif [[ "$DISTRO_NAME" == 'Pop!_OS' ]]; then
      echo 'PopOS';
    else
      echo "${DISTRO_NAME}";
    fi
  elif [[ "$OS" == 'Darwin' ]]; then
    echo 'macOS';
  elif [[ "$OS" == 'CYGWIN' || "$OS" == 'MINGW' || "$OS" == 'MSYS_NT' ]]; then
    echo 'Windows';
  else
    echo "${OS}";
  fi

# Get the OS name, in lowercase and with dashes instead of spaces
[group('tools')]
os_clean:
  #!/usr/bin/env bash
  echo "$(just --justfile "{{ justfile() }}" os | tr '[:upper:]' '[:lower:]' | tr ' ' '-')";

# Checks if the OS is Debian based, returns "true" or "false" as strings.
[group('tools')]
os_debian_based:
  #!/usr/bin/env bash
  OS="$(just --justfile "{{ justfile() }}" os)";
  if [[ "$OS" == "macOS" || "$OS" == "Windows" || "$OS" == "Fedora" || "$OS" == "Fedora Atomic" ]]; then
    echo "false";
  fi
  if [ ! -f "/etc/os-release" ]; then
    echo "false";
  fi
  source "/etc/os-release";
  if [[ "$ID" == "debian" || "$ID_LIKE" == *"debian"* ]]; then
    echo "true";
  else
    echo "false";
  fi

# Get the name of the Linux Desktop Environment
[group('tools')]
os_desktop_clean:
  #!/usr/bin/env bash
  echo "$(echo ${XDG_CURRENT_DESKTOP#ubuntu:} | tr '[:upper:]' '[:lower:]' | tr ' ' '-')";

# List local users
[group('system')]
users:
  awk -F: '$3 >= 1000 && $1 != "nobody" && $0="user: " $1 "   id: " $3 "   home: " $6' /etc/passwd

# Find which process is using a certain port number
[group('system')]
port port_number:
  sudo lsof -i ":{{ port_number }}" || echo "Port doesn't seem to be in use"

# Get a disk partition label using the partition name (eg: nvme0n1p1)
[group('system')]
partition_label partition_name:
	find /dev/disk/ -lname '*{{ partition_name }}' | grep /dev/disk/by-partlabel/ | sed 's/\/dev\/disk\/by-partlabel\///'

# Backup Linux user data
[group('system')]
backup:
  bash "$HOME/Dotfiles/bin/backup-linux-user/backup-linux-user.sh"

# Install and update AI tools
[group('ai')]
ai-install:
  bash "$HOME/Dotfiles/ai/ai.sh"

# View the AI readme
[group('ai')]
ai-docs:
	#!/usr/bin/env bash
	if command -v glow > /dev/null 2>&1 ; then
		glow "$HOME/Dotfiles/ai/README.md"
	else
		cat "$HOME/Dotfiles/ai/README.md"
	fi

# Show your current public IP address
[group('system')]
ip:
  dig +short myip.opendns.com @resolver1.opendns.com

# Run 'update' then 'clean'
[group('system')]
refresh: update clean
	echo "! Both 'update' and 'clean' tasks are finished, a system reboot is recommended."

# Update system packages and apps
[group('system')]
update:
  #!/usr/bin/env bash
  OS=$(just --justfile "{{ justfile() }}" os);
  OS_DEBIAN=$(just --justfile "{{ justfile() }}" os_debian_based);
  echo "i Starting update task";
  echo "! Requesting sudo";
  sudo -v;
  if [[ "$OS" == 'EndeavourOS' ]]; then
    echo 'i EndeavourOS - System updates';
    eos-update --keep-system-running --aur;
  elif [[ "$OS" == 'Fedora' ]]; then
    echo 'i Fedora - Updating packages';
    sudo dnf upgrade --refresh -y > /dev/null 2>&1;
    echo 'i Fedora - Updating firmware';
    sudo fwupdmgr get-updates > /dev/null 2>&1;
    sudo fwupdmgr update -y > /dev/null 2>&1;
  elif [[ "$OS" == 'Fedora Atomic' ]]; then
    echo 'i Fedora Atomic - Updating packages';
    rpm-ostree upgrade --quiet;
  elif [ "$OS_DEBIAN" ]; then
    echo "i $OS - Updating APT packages";
    sudo apt update -y -qq > /dev/null 2>&1;
    # Force package upgrades, even when they're in the phasing stage.
    sudo apt upgrade -y -qq -o APT::Get::Always-Include-Phased-Updates=true > /dev/null 2>&1;
    # Standard package upgrades
    # sudo apt upgrade -y -qq > /dev/null 2>&1;
  fi
  if command -v snap > /dev/null 2>&1 ; then
    echo 'i Snap - Updating packages';
    sudo snap refresh > /dev/null 2>&1;
  fi
  if command -v flatpak > /dev/null 2>&1 ; then
    echo 'i Flatpak - Updating packages';
    flatpak update -y > /dev/null 2>&1;
  fi
  if command -v brew > /dev/null 2>&1 ; then
    echo 'i Homebrew - Updating packages';
    brew update > /dev/null 2>&1;
    brew upgrade > /dev/null 2>&1;
  fi

# Clean packages and temp files
[group('system')]
clean:
  #!/usr/bin/env bash
  OS=$(just os);
  echo "i Starting clean task";
  echo '! Requesting sudo';
  sudo -v;
  if [[ "$OS" == 'EndeavourOS' ]]; then
    echo 'i EndeavourOS - Cleanup packages';
    paccache -rvk2 > /dev/null 2>&1;
    paccache -ruk0 > /dev/null 2>&1;
    sudo pacman -Rns $(pacman -Qtdq) --noconfirm > /dev/null 2>&1;
    echo 'i EndeavourOS - Empty cache';
    rm -rf "$HOME/.cache/"* > /dev/null 2>&1;
    echo 'i EndeavourOS - Remove obsolete packages and caches';
    sudo paccache -ruk0 > /dev/null 2>&1;
    sudo pacman -Rns $(pacman -Qdtq) --noconfirm > /dev/null 2>&1;
    echo 'i EndeavourOS - Remove old system journal logs';
    journalctl --vacuum-time=4weeks > /dev/null 2>&1;
  elif [[ "$OS" == 'Fedora' ]]; then
    echo 'i Fedora - Cleanup packages';
    sudo dnf autoremove -y > /dev/null 2>&1;
    sudo dnf clean all > /dev/null 2>&1;
  elif [ "$(just os_debian_based)" ]; then
    echo "i $OS - Cleanup APT packages";
    sudo apt autoremove -y > /dev/null 2>&1;
    sudo apt clean -y > /dev/null 2>&1;
    sudo apt autoclean -y > /dev/null 2>&1;
  fi
  if command -v flatpak > /dev/null 2>&1 ; then
    echo 'i Flatpak - Cleanup cache';
    rm -rf "$HOME/.cache/flatpak"
    mkdir -p "$HOME/.cache/flatpak"
    echo 'i Flatpak - Cleanup packages';
    flatpak uninstall -y --unused --delete-data > /dev/null 2>&1;
  fi
  if command -v brew > /dev/null 2>&1 ; then
    echo 'i Homebrew - Cleanup packages';
    brew cleanup > /dev/null 2>&1;
  fi

# Info about Just itself
[group('just')]
info:
  @echo "Just Version: $( just --version )"
  @echo "Process ID: {{ just_pid() }}"
  @echo "Binary: {{ just_executable() }}"
  @echo "Current Justfile: {{ justfile() }}"
  @echo "Current Dir: {{ invocation_directory() }}"
